[package]
name = "crumbeez"
version = "0.1.0"
edition = "2021"

[dependencies]
crumbeez-lib = { path = "../crumbeez-lib" }
serde = { workspace = true }
serde_json = { workspace = true }
zellij-tile = "0.41.0"

