[build]
target = "wasm32-wasip1"

[alias]
build-native = "build --target x86_64-unknown-linux-gnu"
check-native = "check --target x86_64-unknown-linux-gnu"
test-native = "test --target x86_64-unknown-linux-gnu"

